- name: Generate ssh key
  openssh_keypair:
    path: "/keys/{{ host.name | default(Default_key_name) }}.id_rsa"
    type: rsa
    size: 4096
    mode: 0600
  loop: "{{ ssh_hosts }}"
  loop_control:
    loop_var: host
