- name: Generate ssh key
  user:
    name: "{{ user_name }}"
    generate_ssh_key: yes
    ssh_key_file: "/keys/{{ key_name }}.id_rsa"
    ssh_key_type: rsa
    ssh_key_bits: 4096
  vars:
    indiv: "{{ host.key_indiv | default(false) }}"
    key_name: "{{ indiv | ternary(host.name, Default_key_name) }}"
    user_name: "{{ lookup('env', 'USER') }}"
  loop: "{{ ssh_hosts }}"
  loop_control:
    loop_var: host
