- name: Add root user to _users
  set_fact:
    _users: "{{ [ansible_user] + ['root'] if ansible_user != 'root' else ['root'] }}"

- name: Print _users
  debug:
    var: _users

- name: Set authorized_key
  authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', '/keys/' + key_name + '.id_rsa.pub') }}"
  loop: "{{ _users }}"
  vars:
    indiv: "{{ host.key_indiv | default(false) }}"
    key_name: "{{ indiv | ternary(host.name, Default_key_name) }}"
