- name: Add root user to _users
  set_fact:
    _users: "{{ [ansible_user, 'root'] | unique }}"

- name: Print _users
  debug:
    var: _users

- name: Set authorized_key
  authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', '/keys/' + key_name + '.id_rsa.pub') }}"
  loop: "{{ _users }}"
  vars:
    indiv: "{{ key_indiv | default(false) }}"
    key_name: "{{ indiv | ternary(inventory_hostname, Default_key_name) }}"
