- import_tasks: add_authorized_key.yml
- import_tasks: allow_sudo.yml

- name: Set ssh_version
  block:
    - command: ssh -V
      register: _result_ssh_version
    - set_fact:
        _ssh_version: "{{ _result_ssh_version.stderr | regex_replace(ptn, '\\1') }}"
      vars:
        ptn: "^OpenSSH_([0-9]+\\.[0-9]+).*"
    - debug:
        var: _ssh_version

- import_tasks: allow_root_login.yml
  when: _ssh_version is version('8.0', '>=')

- import_tasks: allow_root_login_without_include.yml
  when: _ssh_version is version('8.0', '<')
