- import_tasks: add_authorized_key.yml
- import_tasks: allow_sudo.yml

- name: Set _ssh_version
  block:
    - name: Get openssh version
      command: /usr/bin/ssh -V
      register: _result_ssh_version
    - name: Extract major version
      set_fact:
        _ssh_version: "{{ _result_ssh_version.stderr | regex_replace(ptn, '\\1') }}"
      vars:
        ptn: "^OpenSSH_([0-9]+\\.[0-9]+).*"
    - name: Print _ssh_version
      debug:
        var: _ssh_version

- import_tasks: allow_root_login.yml
  when: _ssh_version is version('8.0', '>=')

- import_tasks: allow_root_login_without_include.yml
  when: _ssh_version is version('8.0', '<')
